"""ManagementZone ORM model for AgroLens.

A :class:`ManagementZone` stores the k-means clustering result for a single
field and time window.  Each zone has a label (Low / Medium / High / …), its
mean NDVI/NDRE centroid values, and its GeoJSON geometry (a polygon or
multipolygon subset of the field boundary).

Zones are generated by the Celery ``compute_field_zones`` task and consumed
by the prescription engine to produce per-zone application rates.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Optional

from geoalchemy2 import Geometry, WKBElement
from sqlalchemy import Date, DateTime, ForeignKey, Integer, Numeric, String, func
from sqlalchemy.dialects.postgresql import ENUM as PgEnum, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base

if TYPE_CHECKING:
    from app.models.field import Field
    from app.models.prescription import Prescription


ZONE_LABEL_ENUM = PgEnum(
    "Low",
    "Medium-Low",
    "Medium",
    "Medium-High",
    "High",
    "Very High",
    name="zonelabel",
    create_type=False,
)


class ManagementZone(Base):
    """ORM model for a single management zone within a field.

    Attributes:
        id: UUID primary key.
        field_id: FK → fields.id (CASCADE delete).
        zone_index: 0-based cluster index (0 = lowest NDVI).
        zone_label: Human-readable label from the NDVI-ordered cluster sequence.
        n_zones: Total number of zones this delineation produced (2–5).
        composite_start: First date of the NDVI/NDRE composite window used.
        composite_end: Last date of the composite window.
        ndvi_mean: Mean NDVI value of pixels in this zone.
        ndre_mean: Mean NDRE value of pixels in this zone.
        area_ha: Zone area in hectares.
        geometry: Zone boundary polygon in EPSG:4326.
        created_at: UTC creation timestamp.
    """

    __tablename__ = "management_zones"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Auto-generated UUID primary key.",
    )
    field_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("fields.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → fields.id; cascade deletes zones when field is deleted.",
    )
    zone_index: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="0-based zone index ordered by ascending NDVI centroid.",
    )
    zone_label: Mapped[str] = mapped_column(
        ZONE_LABEL_ENUM,
        nullable=False,
        comment="Human-readable zone label (Low / Medium / High / …).",
    )
    n_zones: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        server_default="3",
        comment="Total number of zones in this delineation run (2–5).",
    )
    composite_start: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        comment="First date of the compositing window used for delineation.",
    )
    composite_end: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        comment="Last date of the compositing window used for delineation.",
    )
    ndvi_mean: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(6, 4),
        nullable=True,
        comment="Mean NDVI centroid value for this zone.",
    )
    ndre_mean: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(6, 4),
        nullable=True,
        comment="Mean NDRE centroid value for this zone.",
    )
    area_ha: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(12, 4),
        nullable=True,
        comment="Zone area in hectares.",
    )
    geometry: Mapped[Optional[WKBElement]] = mapped_column(
        Geometry("MULTIPOLYGON", srid=4326),
        nullable=True,
        comment="Zone boundary as a PostGIS multipolygon in EPSG:4326.",
    )
    created_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Row creation timestamp (UTC).",
    )

    field: Mapped["Field"] = relationship("Field", back_populates="management_zones")
    prescriptions: Mapped[list["Prescription"]] = relationship(
        "Prescription",
        back_populates="management_zone",
        cascade="all, delete-orphan",
    )
